### ISSUE TITLE
Add Style prop to XYPlot component

### ISSUE THREAD

**Issue by ariroseonline** [spotify/reactochart#101]
- Adding a style or plotStyle prop would allow a user to pass in styles to the XYPlot (a component used by most almost users). 
- For reference, SankeyDiagram has a style prop, so this would provide similar parity. 
- A benefit would be that a user wouldn't have to use classname-based styling in their entire implementation and stick to one methodology.

**Comment by mptap** [comment]
@ariroseonline @krissalvador27 Have raised PR for this https://github.com/spotify/reactochart/pull/117

**Comment by krissalvador27** [comment]
resolved via https://github.com/spotify/reactochart/pull/117, will be included in next release! :)
