### ISSUE TITLE
Thoughts on implementing semantic versioning

### ISSUE THREAD

**Issue by krissalvador27** [spotify/reactochart#112]
Hello!

Reactochart doesn't have any official release & versioning procedures and I wanted to propose the official adoption of semantic versioning going forward. Per [semver](https://semver.org/) this would mean

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

**Goals**
- Provide Reactochart users with a more meaningful idea of what each version upgrade entails. Major version upgrades relate to breaking API changes. Minor version upgrades relate to newly added or updated API changes with backward compatibility. Patch versions are for bugs and refactors that don't affect the API.
- Removes subjectivity and human emotion from versioning through rules that are easy to reason with

**What this doesn't solve**
- Documentation: Reactochart is for developers (not machines) and as maintainers we are responsible for documenting the changes of each release. This means being descriptive with our changes via the `changelog`, and updating our docs on gh-pages with each release.

**Comment by krissalvador27** [comment]
closing issue - we're going to go with this approach :)

**Comment by dandelany** [comment]
Belated 👍 👍 from me
