### ISSUE TITLE
measure-text's dependencies are declared as dev-dependencies

### ISSUE THREAD

**Issue by joshbDev** [spotify/reactochart#123]
Right now if there is a conflict of Reactochart's dependency `measure-text`'s dependencies. `measure-text`'s dev-dependencies are declared as regular dependencies. This can cause an error of `Cannot read property 'context' of undefined` if there are conflicts of version.

**Comment by ekh64** [comment]
+1 to this, it's preventing me from upgrading a library that has a reactochart dependency since my main project is powered by `react-scripts`

**Comment by scottsheffield** [comment]
+1 to this also, it's preventing someone I know from upgrading a library that has a reactochart dependency since their main project is powered by `react-scripts`

**Comment by ekh64** [comment]
I've forked the repo and will put in a PR there. Otherwise we can maybe use that fork instead if it doesn't get merged https://github.com/ekh64/measure-text

**Comment by krissalvador27** [comment]
Thanks @ekh64! Will mark this issue as taken, please let me know if you need any support 😄

**Comment by ekh64** [comment]
I'm having trouble getting their CI to pass, it's pretty unmaintained, with things working locally and then failing on CI...

If this fails, can you remove the dependency?

**Comment by krissalvador27** [comment]
should be fixed in v1.4.1 👍
