### ISSUE TITLE
Deprecate Moment.js

### ISSUE THREAD

**Issue by ekh64** [spotify/reactochart#158]
Moment is big and bloats bundles, would be nice to deprecate that use in favor of [d3-time-format](https://github.com/d3/d3-time-format) or [d3-time](https://github.com/d3/d3-time)

Some of this functionality might be bundled into the standard `d3` import by default.

**Comment by krissalvador27** [comment]
Going to take a look into this!

**Comment by krissalvador27** [comment]
On investigation, deprecating moment in favor of [d3-time-format](https://github.com/d3/d3-time-format) would be a breaking change. We currently allow users to pass in a format array that contains strings that map to various [moment formats](https://devhints.io/moment#formatting-1), e.g. `['YYYY', 'MM/YY']`. d3 time format uses [strptime and strftime](https://github.com/d3/d3-time-format/blob/master/README.md#locale_format) for their format function.

That said, I'm still for deprecating moment to reduce the library's bundle size and utilize as much of d3 as we can. Will include this in our v2 release.
