### ISSUE TITLE
Modularize lodash

### ISSUE THREAD

**Issue by ekh64** [spotify/reactochart#159]
Lodash can be modularized, but the results can look gross. I took a [stab on my fork](https://github.com/ekh64/reactochart/commit/63b553aaa894fd365b9df4e11bd817e87c08f91c), but the result was pretty gnarly (and not 100% functional)

Maybe there's a way to do this without explicit imports? Maybe something in the bundling?

**Comment by krissalvador27** [comment]
Going to experiment with having lodash modularized during the build process 😄

**Comment by krissalvador27** [comment]
Addressed this in #163 and went a step further in #164 to replace some lodash imports with their native counterparts. Will go out in next minor release!
