### ISSUE TITLE
[Infra] Integrate cross-env into scripts using ENV variables

### ISSUE THREAD

**Issue by krissalvador27** [spotify/reactochart#161]
Our build and test scripts set env variables that fail for developers on Windows OS.
We should leverage [cross-env](https://www.npmjs.com/package/cross-env) on scripts that require an env variable.

**Comment by rbrishabh** [comment]
Can I take this up?
I would need some help getting started! 

Thanks!

**Comment by krissalvador27** [comment]
Hey @rbrishabh!

Would require an added devDependency of [cross-env](https://www.npmjs.com/package/cross-env) and updating any scripts that set NODE or BABEL environments to use cross-env. Let me know if you decide to work on this and I'll assign you. The scripts should then work for Mac and Windows OS 👍
