### ISSUE TITLE
Deprecate numeral.js

### ISSUE THREAD

**Issue by krissalvador27** [spotify/reactochart#165]
[Numeral.js](https://github.com/adamwdraper/Numeral-js) is no longer maintained. Would recommend switching to [d3 format](https://github.com/d3/d3-format). This would be a breaking change as we allow users to send a format array, where each string in the format array maps to numeral's way of [formatting](http://numeraljs.com/#format).

This would also reduce our bundle size and allow us to leverage more packages already imported by our use of d3.

**Comment by krissalvador27** [comment]
Hey @acmei, thanks for taking this on! For this change I would make your PR off the `2.0.0-rc.0` branch, not master since this will be going out in v2.

**Comment by acmei** [comment]
Merged fix with PR #169
