### ISSUE TITLE
Decorate XYPlot onMouseEnter and onMouseLeave events

### ISSUE THREAD

**Issue by krissalvador27** [spotify/reactochart#176]
We decorate `onMouseMove`, `onMouseDown`, `onMouseUp`, `onClick` with helpful information like xScale, yScale, xValue and yValue. We should decorate `onMouseEnter` and `onMouseLeave` for consistency.

**Comment by tanayv** [comment]
Hey @krissalvador27!

I can take this up. Just to clarify: decorating the `onMouseEnter` and `onMouseLeave` events would involve adding a binding to the `onXYMouseEvent` [function](https://github.com/spotify/reactochart/blob/755864f1b5328da90109487b3e5aae44c9c7406b/src/XYPlot.js#L203) right? 

Let me know if that's what you had in mind, and I can have a PR for this ready. Thanks!

**Comment by krissalvador27** [comment]
Hey @tanayv!

Sorry for the delay, I've been out of office. What you said is right! 

Let me know if you need any other support :)

**Comment by krissalvador27** [comment]
Hey @tanayv, do you plan on taking up this issue?

**Comment by tanayv** [comment]
Yes, sorry for the delay. I just had one thing I was slightly confused about: 
```
  onMouseMove = this.onXYMouseEvent.bind(this, 'onMouseMove');
  onMouseDown = this.onXYMouseEvent.bind(this, 'onMouseDown');
  onMouseUp = this.onXYMouseEvent.bind(this, 'onMouseUp');
  onClick = this.onXYMouseEvent.bind(this, 'onClick');

  // Decorate onMouseEnter and onMouseLeave
  onMouseEnter = this.onXYMouseEvent.bind(this, 'onMouseEnter');
  onMouseLeave = this.onXYMouseEvent.bind(this, 'onMouseLeave')

  // Possibly redundant?
  onMouseEnter = event => this.props.onMouseEnter({ event });
  onMouseLeave = event => this.props.onMouseLeave({ event });
```

I couldn't deduce if there was a reason/use case for why the two events were declared in a different way compared to the other events, and I was going through the code base to understand but I haven't been able to do so. If I bind them using the onXYMouseEvent, should I go ahead and remove their original declarations?

**Comment by krissalvador27** [comment]
I believe it's to namespace the event object so that it returns `{ event: { ... } }` as the callback argument. Similar in style to how `getMouseOptions` adds the event object to the event key.

So yes, I would remove the original declarations :)
