### ISSUE TITLE
Convert test suite from mocha to jest

### ISSUE THREAD

**Issue by krissalvador27** [spotify/reactochart#183]
Our tests currently leverage [mocha](https://mochajs.org/), [chai](https://www.chaijs.com/) and [sinon](https://sinonjs.org/). We should migrate our test suite to use [jest](https://jestjs.io/).

- It's Spotify's preferred Javascript test framework and aligns web-scripts out of the box eslint configuration. See [here](https://github.com/spotify/web-scripts#related-projects-we-use).
- Jest is a kitchen sink that works out of the box, removing the need to manage multiple dependencies.
- Jest is overtaking mocha in community adoption (as of 10/29/19 5.1 million vs 3.3 million weekly downloads). Adopting the tools used more frequently by our community can reduce barrier to contribution.

**Comment by ekh64** [comment]
Oh hey, we did this!
