### ISSUE TITLE
Proposed API changes for v0.4.x

### ISSUE THREAD

**Issue by dandelany** [spotify/reactochart#47]
I've picked up work on Reactochart again and am working towards a new release with more features & improved docs & tests. As a part of this release, there are some rough parts of the API that I'd like to propose changing. Please comment here if you have any thoughts or objections.

### 1. Rename all `getThing` ("getter") props to just `thing`; update them to accept either a constant value or accessor function (when possible).

Currently there are a number of special "getter" props which start with `get` (eg. `getX`/`getY`, `getClassName`) which tell the chart how to access a data value & determine a prop for each thing in a series (eg. a bunch of bars in a bar chart). However, many of these currently need *two* separate props - a "getter" prop for when the user wants it to be dynamic, and a regular prop if the user wants just a single static value. For example, `BarChart` has a `getClass` prop (a function which dynamically assigns a class to each bar), *and* a `barClassName` prop (a string className, which would be applied to all bars).

Instead, I propose that we combine them into a single prop, without `get` in the prop name. Such props would allow either a simple individual value to be passed, or (whenever possible) a function which would be called with each datum. Examples:

OLD: `<BarChart getClass={(d) => d.name} />` OR `<BarChart barClassName="my-bar" />`
NEW: `<BarChart barClassName={(d) => d.name} />` OR `<BarChart barClassName="my-bar" />`

The main advantages here are consistency, reducing the number of props, and allowing as many props as possible to take either static or dynamic (function) values.

Affected props: `getX` --> `x`, `getY` --> `y`, `getClass` --> `className` (or barClassName, etc.), `getArea` --> `area`, `getValue` --> `value`, etc.

### 2. Deprecate string/number/null shorthand for "getter" props.

Closely related to #1 above. Currently "getter" props like `getX`/`getY` accept functions, but they also accept a "shorthand" string/number which is transformed into a key/index accessor function. For example, if you render `<BarChart getX={'foo'} />`, this is internally turned into the function `(d) => d.foo` which is called on each datum to get the bar's X value. [See the docs for more info on this behavior](http://spotify.github.io/reactochart/docs/build/#/getters-and-accessors).

This can be convenient sometimes, but adds complexity to Reactochart code and requires a lot of explanation in the docs. More importantly, it conflicts with #1 above: If we deprecated `getClass` in favor of `className` but did *not* deprecate these shorthand accessors, something like `<... className="foo" />` would become ambiguous - does it mean "use the string 'foo' for my className" or "use the function `d => d.foo` to determine className"? For this reason, we must do BOTH #1 and #2, or neither. 

The only downside I see here is that users will probably replace a lot of their shorthand `getX` and `getY`s with arrow functions, eg.:

OLD: `<BarChart getX={0} ... />`
NEW: `<BarChart x={(d) => x[0]} ... />`
OLD: `<BarChart getX="x" ... />`
NEW: `<BarChart x={(d) => d.x} ... />`

This is fine for charts which aren't re-rendered, but can cause performance issues for those which are interactive or need to be re-rendered often - because by creating a new arrow function on each render, the user would cause `oldProps.x !== newProps.x`, causing the entire chart to re-render every time. The performant solution is for the user to create the accessor function once, outside of their `render` function, so that it `===`s itself on every new render. This is definitely a bit less convenient, but is already an issue with any props which pass an arrow function, so React developers should already be familiar with it.

Affected props: `x` (`getX`), `y` (`getY`), and any other props which use shorthand string/number getters.

### 3. Deprecate combined `thing={{x:..., y:...}}` props in favor of separate `xThing` and `yThing` props
Currently there are several combined "X/Y" axis-related props that accept either an `{x, y}`-shaped object, or a single value to be applied to both X and Y axes. I want to replace these with separate `xThing` and `yThing` props, for example:

OLD: `<BarChart domain={{x: xDomain, y: yDomain}} />` or `<... domain={commonDomain} />`
NEW: `<BarChart xDomain={xDomain} yDomain={yDomain} />`

The old way is potentially confusing (since there are two different behaviors) and it adds some unnecessary complexity in our components. Furthermore, it's problematic for `PureComponent` performance optimization: we expect that when a user re-renders a chart, any props which have not changed since the last render will `===` their old values. However, when users render charts using object literals, a new object literal is created on every render, so old props `!==` the new ones, making it harder to avoid unnecessary re-renders.

Affected props: `domain` --> `xDomain`/`yDomain`, `scaleType` --> `xScaleType`/`yScaleType`, `nice` --> `xNice`/`yNice`, `invertScale` --> `invertXScale`/`invertYScale`.

### 4. Deprecate combined `thing={{top:..., bottom:..., left:..., right:...}}` props in favor of separate `thingTop`, `thingBottom`, `thingLeft`, `thingRight` props.

Essentially the same thing as #3 except with top/bottom/left/right instead of x/y, & same rationale.

OLD: `<XYPlot margin={{top: 12, right: 50}} ... />`
NEW: `<XYPlot marginTop={12} marginRight={50} ... />`

If we wanted, we could still have a general `margin` prop that accepts a *number* that would be applied to all top/bottom/left/right, for more convenience when you want to pass the same number for all 4 values, but I'm not sure how common a use case that is.

Affected props: `padding` --> `paddingTop`/`paddingBottom`/`paddingLeft`/`paddingRight`,  `margin` --> `marginTop`/`marginBottom`/`marginLeft`/`marginRight`, `spacing` --> `spacingTop`/`spacingBottom`/`spacingLeft`/`spacingRight`

**Comment by krissalvador27** [comment]
@dandelany for #4 is it possible to also have a general xyPlotStyle or an even more generalized itemStyle (unsure if that's the best name) object for all components that just takes an object and camelcased css properties that would be applied to the root container?

```
<XYPlot 
  itemStyle={{ marginTop: 12, paddingRight: 8}}
  ... />
```
It's a play on barStyle and lineStyle which I like a lot. It provides flexibility for people who prefer less props and passing styles as objects instead of unpacking & mapping them to each prop individually

**Comment by dandelany** [comment]
Thanks @krissalvador27 - the reason `margin` and `padding` are separate props for `XYPlot` is because they aren't actually `margin`/`padding` **styles**, they have a special meaning for `XYPlot`:

`margin` is the space between the boundary of the SVG and the boundary of the actual chart plot contained within - ie. where all of the axis labels are drawn. `padding` is empty space within the chart plot itself; eg. when you have a bar chart where one bar is all the way at one of the edges, padding is needed so the width of the bar doesn't overhang the axis line. Both are usually determined automatically by `XYPlot`, but can be overridden manually with these props. Since things are actually drawn in these areas (bars, ticks, labels), they can't just be CSS padding/margin.

I'll make this clear in the new docs. I do feel a bit badly "overloading" the terms to mean something different than usual for `XYPlot`, but I really couldn't come up with anything better to call them :) If you have any better suggestions I'm open to hearing them.

**Comment by dandelany** [comment]
Whoops, misclicked and closed this 😛 reopened

**Comment by joshbDev** [comment]
@dandelany I think this all makes a lot of sense. Thanks for taking the initiative on such a sweeping change!

**Comment by dandelany** [comment]
Closing this as `0.4.1` has been released, which contains these changes.
