### ISSUE TITLE
Namespace default classNames

### ISSUE THREAD

**Issue by dandelany** [spotify/reactochart#51]
Currently by default we render (& style) elements with very general classNames eg. `chart-bar` or `xy-plot` which could accidentally collide with classNames that users would use in their apps. Per suggestion from @ekh64 we should prefix these with a namespace eg `rc-chart-bar`. `rc-` seems best, but I want to check out `rc-slider` (common slider library) and similar to make sure we don't use the same prefix they do.

**Comment by mindyyuan** [comment]
I believe this is resolved? @krissalvador27

**Comment by krissalvador27** [comment]
This is resolved via #66
