### ISSUE TITLE
Specifying ticks prop on XAxis or YAxis throws error

### ISSUE THREAD

**Issue by cloudonshore** [spotify/reactochart#8]
the error is in `/src/utils/Scale.js`

`Scale.js:104 Uncaught ReferenceError: combineDomains is not defined`

It seems that that function should be imported from `lib/utils/Data.js` but it isn't included in the `Scale` module.

**Comment by dandelany** [comment]
@cloudonshore I wasn't able to replicate this... I think I may have given you bad info about which branch to use - the most recent up to date branch is actually `0.2.1` not `0.2.x`, as `0.2.x` was already merged to master. Try again on the `0.2.1` branch and see if you still have issues.

**Comment by dandelany** [comment]
PS: we should maybe do a code audit this week and, if all is well, merge `0.2.1` to master.

**Comment by krissalvador27** [comment]
Also unable to replicate this. `/src/utils/Scale.js` imports `combineDomains` from `src/utils/Data.js` in current version.
